backend:
  name: github
  branch: master
  repo: conqueror23/OfficialSite

media_folder: static/img
public_folder: src/cms/contents

collections:
  - name: "asia"
    label: "Asia"
    folder: "src/cms/contents/asia"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "author", name: "author", widget: "string" }
      - { label: "thumbnail", name: "thumbnail", widget: "markdown" }
      - { label: "cnContent", name: "cnContent", widget: "markdown" }
      - { label: "enContent", name: "enContent", widget: "markdown" }
  - name: "indo"
    label: "Indo"
    folder: "src/cms/contents/indo"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "author", name: "author", widget: "string" }
      - { label: "thumbnail", name: "thumbnail", widget: "markdown" }
      - { label: "cnContent", name: "cnContent", widget: "markdown" }
      - { label: "enContent", name: "enContent", widget: "markdown" }
  - name: "security"
    label: "Security"
    folder: "src/cms/contents/security"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "author", name: "author", widget: "string" }
      - { label: "thumbnail", name: "thumbnail", widget: "markdown" }
      - { label: "cnContent", name: "cnContent", widget: "markdown" }
      - { label: "enContent", name: "enContent", widget: "markdown" }
  - name: "settings"
    label: "settings"
    folder: "src/cms/settings"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
