backend:
  name: gitlab
  branch: master
  # setting for gitlab
  repo: bruce.wang/OfficialSiteNetlifyCMS
  auth_type: implicit
  app_id: 4ae72c5110c10a90fbed6af2de61a8b4c3a82237091ff9f1139b4f1b7f4d8580
  api_root : http://c7git.acy.svr/api/v4
  base_url: http://c7git.acy.svr/
  auth_endpoint: oauth/authorize

media_folder: static/img
public_folder: src/cms/contents

collections:
  - name: "asia"
    label: "Asia"
    folder: "src/cms/contents/asia"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "author", name: "author", widget: "string" }
      - { label: "thumbnail", name: "thumbnail", widget: "markdown" }
      - { label: "cnContent", name: "cnContent", widget: "markdown" }
      - { label: "enContent", name: "enContent", widget: "markdown" }
  - name: "indo"
    label: "Indo"
    folder: "src/cms/contents/indo"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "author", name: "author", widget: "string" }
      - { label: "thumbnail", name: "thumbnail", widget: "markdown" }
      - { label: "cnContent", name: "cnContent", widget: "markdown" }
      - { label: "enContent", name: "enContent", widget: "markdown" }
  - name: "security"
    label: "Security"
    folder: "src/cms/contents/security"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "author", name: "author", widget: "string" }
      - { label: "thumbnail", name: "thumbnail", widget: "markdown" }
      - { label: "cnContent", name: "cnContent", widget: "markdown" }
      - { label: "enContent", name: "enContent", widget: "markdown" }
  - name: "settings"
    label: "settings"
    folder: "src/cms/settings"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
